apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
    #annotations:
  #service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - name: jenkins
      port: 80
      targetPort: 8080
