apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-role
rules:
  - apiGroups: [ "" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
    resources:
      - services
      - podtemplates
      - configmaps
      - secrets
      - namespaces
      - pods
  - apiGroups: [ "apps" ]
    resources:
      - deployments
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
    resources:
      - customresourcedefinitions


