apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: poc
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app
          image: docker.io/vamseeds/explore-python-k8s:latest
          ports:
            - containerPort: 8080
