apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: poc
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: app
      port: 8080
      targetPort: 8080
